setting:
  request: # 网络请求设置
    timeout: 10 # gitee友链配置
    ssl: false  # gitee友链配置

  gitee_friends_links: # gitee友链配置
    enable: false
    type: normal # volantis用户请在这里填写 volantis
    owner: Zfour # 填写你的gitee用户名
    repo: zfour-friends # 填写你的gitee仓库名
    state: open # 填写抓取的issue状态(open/progressing/closed)

  github_friends_links: # github友链配置
    enable: false
    type: normal # volantis用户请在这里填写 volantis
    owner: Zfour # 填写你的github用户名
    repo: zfour-friends # 填写你的github仓库名
    state: open # 填写抓取的issue状态(open/closed)

  block_word: # 屏蔽sitemap链接关键词
    - 'index'
    - 'json'
    - 'tags'
    - 'categories'
    - 'record'
    - 'sort'

  block_chars: # 屏蔽sitemap获取标题的分割字符
    - '|'
    - '::'
    - '-'
    - '·'
    - '绒布球'

  block_site: # 屏蔽站点
    - https://example.com/
